# Generated by Django 5.2.3 on 2025-09-10 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsproject', '0006_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='shipping_first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'This field may only contain letters, spaces, and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='shipping_last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'This field may only contain letters, spaces, and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='shipping_phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\+?\\d{10}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='shipping_zipcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\+?\\d{6}$', 'Enter a valid ZIP/Postal code.')]),
        ),
    ]
