# Generated by Django 5.2.3 on 2025-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsproject', '0008_order_bank_name_order_card_last4_order_card_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_provider',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
